eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18080/eureka/
server:
  port: 18081
spring:
  application:
    name: service-zuul
  boot:
    admin:
      client:
        url: http://localhost:50000
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
info:
  app:
    name: "Zuul Server Pro"
    description: "This is a Zuul Server"
    version: "v1.0"
    status: "success"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS