eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18080/eureka/
server:
  port: 8764
spring:
  application:
    name: service-ribbon
  boot:
    admin:
      client:
        url: http://localhost:50000
user-service:
  ribbon:
    RulePredicateClasses: com.netflix.loadbalancer.RandomRule