eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18080/eureka/
server:
  port: 8764
spring:
  application:
    name: service-ribbon
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000