server:
  port: 8890

spring:
  application:
    name: new-service
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:50000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18080/eureka/

info:
  app:
    name: "New Server Pro2"
    description: "This is a New Server Node"
    version: "v1.0"
    status: "success"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS