spring:
  application:
    name: new-service
    #监控
  zipkin:
    base-url: http://localhost:9411
  security:
    user:
      name: "client"
      password: "client"
#端口
server:
  port: 18083

#注册中心客户端的配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18080/eureka/
  instance:
    # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 5
    # 发呆时间，即服务续约到期时间（缺省为90s）
    lease-renewal-interval-in-seconds: 10
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS